name: AFKPlus-OG
version: '${version}'
main: net.lapismc.afkplusog.AFKPlusOG
api-version: '${apiVersion}'
softdepend: [PlaceholderAPI, Essentials, LuckPerms]
authors: [Dart2112, NotAlexNoyle]
description: AFK for professional servers.
